#!/bin/sh

# This command should match the equivalent command found in
# the Makefile.inc file in the root of the repo.
version=`git describe --always --dirty --tags --abbrev=1`

gitcommit=`git rev-parse HEAD`
gitbranch=`git branch | grep \* | cut -d ' ' -f2`
goversion=`go version | head -n 1`
builddate=`date -u +"%Y-%m-%d %H:%M %Z"`
buildepoch=`date -u +"%s"`

if test "`uname`" == "Darwin"; then
    platform=`sw_vers | cut -f 2 | fmt`
else
    platform=`uname`
fi

echo "CURRENT_TIME $builddate"
echo "CURRENT_EPOCH $buildepoch"
echo "STABLE_GIT_COMMIT $gitcommit"
echo "STABLE_GIT_VERSION $version"
echo "STABLE_GIT_BRANCH $gitbranch"
echo "STABLE_PLATFORM $platform"
