apiVersion: apps/v1
kind: Deployment
metadata:
  name: {BOTNAME}-phoebot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {BOTNAME}-phoebot
  template:
    metadata:
      name: {BOTNAME}-phoebot
      labels:
        app: {BOTNAME}-phoebot
    spec:
      imagePullSecrets:
      - name: docker
      containers:
      - name: {BOTNAME}-phoebot
        image: index.docker.io/nugget/phoebot
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: {BOTNAME}-phoebot-config
