apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: phoebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoebot
  template:
    metadata:
      name: phoebot
      labels:
        app: phoebot
    spec:
      imagePullSecrets:
      - name: docker
      containers:
      - name: phoebot
        image: index.docker.io/nugget/phoebot
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: phoebot-config
        - secretRef:
            name: phoebot-secret
        volumeMounts:
        - mountPath: /phoebot
          name: phoebot-data
      volumes:
      - name: phoebot-data
        nfs:
          server: 172.28.20.8
          path: "/volume1/rancher/phoebot"
